### ISSUE TITLE
Possible bug in toHaveText matcher

### ISSUE THREAD

**Issue by danascheider** [unindented/jasmine-jquery-matchers#1]
Hello, I've been seeing some unexpected behavior from the toHaveText matcher, and wanted to let you know in case it's a bug. I am using Jasmine-Node to test a Backbone.js app. The test in question is this:
<pre><code>it('doesn\'t include backlogged tasks', function() {
  data.taskCollection.models[0].set('backlog', true);
  view.render();
  expect(view.$('div.dash-widget[data-name=tasks] div.huge')).toHaveText(data.taskCollection.length - 1);
});</code></pre>This test should fail because I have noticed the app does indeed fail to meet the expectation. Indeed, when I change the expectation, it does fail:
<pre><code>expect(view.$('div.dash-widget[data-name=tasks] div.huge').text().indexOf(data.taskCollection.length - 1).toBeGreaterThan(-1);</code></pre>This generates the following output:<pre><code>  1) Dashboard Top Widget View elements task widget doesn't include backlogged tasks
   Message:
     Expected -1 to be greater than -1.
   Stacktrace:
     Error: Expected -1 to be greater than -1.
    at null.<anonymous> (/private/var/www/spec/views/partialViews/dashboardTopWidgetsViewSpec.js:79:116)</code></pre>I believe the matcher uses `indexOf` to test for the presence of a string literal. This seems very straightforward, and I know the behavior of my app because I have tested it both manually and with Selenium. Any ideas?

Thank you for this tool, it's very helpful!

**Comment by unindented** [comment]
The matcher uses `test` when you pass a regular expression, and `indexOf` in all other cases. You can check out the code here, it's pretty straightforward: https://github.com/unindented/jasmine-jquery-matchers/blob/0c1c11094beb623da43911d9165110f568fafd56/src/matchers.js#L127-L138

Can you create a small test case that I can easily reproduce? Something like the tests that are already there would be awesome: https://github.com/unindented/jasmine-jquery-matchers/blob/0c1c11094beb623da43911d9165110f568fafd56/test/specs/matchers.js#L94-L114

Thank you for your help!

**Comment by danascheider** [comment]
I’ll see what I can come up with. I won’t have time today, unfortunately, because one of my servers got hacked and I have to get  my sites back online. I should be able to put something together by the end of the weekend.

**Comment by unindented** [comment]
Sorry to hear that. No rush.
